version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5555:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    networks:
      - app_network

  redis:
    image: redis:6.2.7
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - app_network

  app:
    build: .
    command: >
      sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000 & bundle exec sidekiq -C ./config/sidekiq.yml"
    volumes:
      - .:/app
      - bundle:/bundle
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    # environment:
    #   SECRET_KEY_BASE: ${SECRET_KEY_BASE:-73898ac81a634c676ddc52159c56741731a1c10e22e93434d531119ef29099474a465064aa8a75b557541cdabb2398efc8f6e5b64f996c05912e4b93e01645bd}
    networks:
      - app_network
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  bundle:

networks:
  app_network:
    driver: bridge